status = [
  "ci 1.5.2 - ubuntu-latest",
  "ci 1.5.2 - windows-latest",
  "ci 1.5.2 - macOS-latest",
  "docbuild",
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
